services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - vdo-maker-network

  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_VERSION=v1
      - FRONTEND_URL=http://localhost:5173
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
      - JWT_EXPIRES_IN=7d
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-api-key-here}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID:-your-google-cloud-project-id}
      - PIAPI_API_KEY=${PIAPI_API_KEY:-your-piapi-key-here}
      - PIAPI_BASE_URL=https://api.piapi.ai
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=50MB
      - ALLOWED_FILE_TYPES=mp4,mov,avi,mp3,wav,png,jpg,jpeg
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - ./server:/app
      - /app/node_modules
      - backend-uploads:/app/uploads
      - backend-db:/app/prisma
    networks:
      - vdo-maker-network

networks:
  vdo-maker-network:
    driver: bridge

volumes:
  backend-uploads:
  backend-db:
