services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=vdo_maker
      - POSTGRES_USER=vdo_maker_user
      - POSTGRES_PASSWORD=vdo_maker_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vdo-maker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vdo_maker_user -d vdo_maker"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - vdo-maker-network

  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vdo-maker-network

networks:
  vdo-maker-network:
    driver: bridge

volumes:
  postgres_data:
